version: "3.7"

services:


  api:
    image: api-ctt
    environment:
      - STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET
    ports:
      - "8090:8090"
    volumes:
      - app-models:/app/models
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    environment:
      - node.name=es01
      - node.master=true
      - node.data=true
      - cluster.name=elk-docker-swarm-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
#      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
#      - xpack.security.enabled=$ELASTIC_SECURITY
    ports:
      - "9200:9200"
    expose:
    - "9200"
    networks:
    - elastic
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
#      - ./snapshots:/mnt/snapshots
#      - ./config/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.7.1'
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_USERNAME: elastic
#      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    ports:
      - '5601:5601'
    networks:
    - elastic
    expose:
    - "5601"
    depends_on:
    - elasticsearch

volumes:
  app-models:
    driver: local
  elastic-data:
    driver: local

networks:
  elastic:
    driver: bridge